### ISSUE TITLE
CSV fails with non-small file

### ISSUE THREAD

**Issue by clach04** [clach04/handbase-py#1]
Small file fine. Errors:

1.     `urllib2.HTTPError: HTTP Error 500: Internal Server Error`
2.     `urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>`

server disconnects without error on larger file :-(

    Traceback (most recent call last):
      File "handbase/web/remote.py", line 309, in <module>
        sys.exit(main())
      File "handbase/web/remote.py", line 297, in main
        put_db(server_url, dbname, csv_bytes, dbtype=dbtype)
      File "handbase/web/remote.py", line 217, in put_db
        put_url(put_db_url, body, headers=headers, verb=POST)
      File "handbase/web/remote.py", line 148, in put_url
        response = urlopen(request)
      File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 429, in open
        response = self._open(req, data)
      File "/usr/lib/python2.7/urllib2.py", line 447, in _open
        '_open', req)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1235, in http_open
        return self.do_open(httplib.HTTPConnection, req)
      File "/usr/lib/python2.7/urllib2.py", line 1205, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>

or:

    Traceback (most recent call last):
      File "./handbase/web/remote.py", line 320, in <module>
        sys.exit(main())
      File "./handbase/web/remote.py", line 297, in main
        put_db(server_url, dbname, csv_bytes, dbtype=dbtype)
      File "./handbase/web/remote.py", line 217, in put_db
        put_url(put_db_url, body, headers=headers, verb=POST)
      File "./handbase/web/remote.py", line 148, in put_url
        response = urlopen(request)
      File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 500: Internal Server Error

- [x] upload a small test case that works (demo from readme)
- [x] create and upload a larger test case that fails, based on the demo from readme (duplicate rows)
- [x] compare with web browser sent payload to debug server

**Comment by clach04** [comment]
The file that shows this issue has non-ascii characters, unclear if significant or size related.

**Comment by clach04** [comment]
small file that WORKS, unix newlines:

    quote,nsfw
    """Off with his head!"", the Queen said.",0
    It's the luck of the Irish!,0
    "Expletive-deleted, expletive-deleted you expletive-deleted.",1
    "This is a teeny, tiny bit longer than sixty bytes/characters.",0
    "Ready?
    Steady?
    Go!",0
    "Annother.
    Newline?
    Demo.",0

**Comment by clach04** [comment]
Bug test case attached bug_174_rows.csv

  * 5115 bytes
  * 5.5Kb
[bug_174_rows.csv](https://github.com/clach04/handbase-py/files/13926796/bug_174_rows.csv)

Problem caused by not sending correct data length.
